### ISSUE TITLE
Blitz updates required

### ISSUE THREAD

**Issue by ukgamer** [ukgamer/gmod-arcademachines#21]
@simlzx 

Needs to be wrapped in FONT:Exists checks

https://github.com/ukgamer/gmod-arcademachines/blob/98f66ac308b946315d5ca86918684f746b9e4d62/lua/arcademachine_games/blitz.lua#L761-L793

Why do these need to exist

https://github.com/ukgamer/gmod-arcademachines/blob/98f66ac308b946315d5ca86918684f746b9e4d62/lua/arcademachine_games/blitz.lua#L115-L140

**Comment by simlx** [comment]
Updated
https://github.com/ukgamer/gmod-arcademachines/pull/22/commits/02249c6cb52d5de827fa14572f8db7df3fe04367
