### ISSUE TITLE
Blitz, No attract screen.

### ISSUE THREAD

**Issue by henkeswe** [ukgamer/gmod-arcademachines#26]
There is no attract screen for the game "Blitz"
Without one it's just a black screen which makes it seem broken and bland before you actually play it.

**Comment by henkeswe** [comment]
@simlzx Fix it!

**Comment by simlx** [comment]
Added! https://github.com/simlzx/gmod-arcademachines/commit/faf7a64908c9d432bddacdb4aa6a4723bee4137d
