### ISSUE TITLE
Blitz - space to start doesn't work

### ISSUE THREAD

**Issue by ukgamer** [ukgamer/gmod-arcademachines#42]
@simlzx 

Pressing space to restart doesn't work when 1 coin is left.

Steps to reproduce:
- Put two coins in
- Die
- Press space to restart, it works
- Die again

The prompt to press space appears but pressing space just reduces the coin count to 0 and game does not restart.

**Comment by ukgamer** [comment]
Bump @simlzx

**Comment by simlx** [comment]
@ukgamer
is fixed now https://github.com/ukgamer/gmod-arcademachines/pull/47/commits/f9d8d9a625a15736fb90ba3ee3c3d104d4930497
