### ISSUE TITLE
GetDriver (a nil value) [arcade_cabinet/init.lua:113]

### ISSUE THREAD

**Issue by rayzox57** [ukgamer/gmod-arcademachines#64]
Hello here is the error that I could find: If you are local and you put your game in "reduced" for a few seconds, this error will start in a loop, I tried to correct it by checking the nil, but this only delays the problem because then it is when using the machine that it will no longer work. I have the impression that this bug occurs when there are more than 6 arcades on the map. I tell myself that it's local so it doesn't matter, but if it happens on servers it may cause a problem... Can you look? Thanks :)

Error Report :
```
[gmod-arcademachines] addons/gmod-arcademachines/lua/entities/arcade_cabinet/init.lua:113: attempt to call method 'GetDriver' (a nil value)
  1. unknown - addons/gmod-arcademachines/lua/entities/arcade_cabinet/init.lua:113 (x594)
```

**Comment by rayzox57** [comment]
PS : I Use a FGD to spawn entities directly on Hammer : 

arcade_placer.fgd (i change format to upload here) : [arcade_placer.txt](https://github.com/ukgamer/gmod-arcademachines/files/9227959/arcade_placer.txt)

And i add this in **lua/entities/arcade_cabinet/init.lua** :
`function ENT:KeyValue( key, value )
    if(key == "currentGame") then
        self:SetCurrentGame(value)
    elseif(key == "cost") then
        self:SetCost(value)
    end
end
`

**Comment by ukgamer** [comment]
Hi,

I think this is related to the timer that was setting the networked variable for the seat not firing for some reason. I was only able to replicate this myself by setting the timer to some huge value i.e. 30 seconds.

I've added your KeyValue code to support spawning from FGDs and changed the seat spawning logic to happen on first Think of the cabinet (or if the seat is somehow removed). I also added some IsValid checks on Think and Use just in case.

Can you let me know if this fixes your issue?

**Comment by rayzox57** [comment]
Hello, and thank you for the very quick response! I'll test it and get back to you very soon!

**Comment by rayzox57** [comment]
Your solution seems to work ^^ I'm going to leave the machine in a mess to see if it supports more than 10 minutes (just to be sure)
